// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilmDukkaniDbContext))]
    [Migration("20251127121329_AddMemberMovieListEntities")]
    partial class AddMemberMovieListEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Aksiyon",
                            CreatedDate = new DateTime(2025, 10, 9, 20, 12, 59, 638, DateTimeKind.Local).AddTicks(118),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7585)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Macera",
                            CreatedDate = new DateTime(2025, 10, 7, 8, 20, 46, 920, DateTimeKind.Local).AddTicks(1521),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7590)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Dram",
                            CreatedDate = new DateTime(2024, 5, 10, 6, 44, 42, 933, DateTimeKind.Local).AddTicks(9122),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7591)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Korku",
                            CreatedDate = new DateTime(2024, 11, 18, 23, 47, 50, 853, DateTimeKind.Local).AddTicks(7558),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7593)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Bilim Kurgu",
                            CreatedDate = new DateTime(2024, 4, 23, 16, 3, 1, 556, DateTimeKind.Local).AddTicks(2532),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7595)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Komedi",
                            CreatedDate = new DateTime(2024, 4, 1, 20, 55, 41, 277, DateTimeKind.Local).AddTicks(9953),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7598)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Gerilim",
                            CreatedDate = new DateTime(2025, 7, 29, 7, 38, 37, 268, DateTimeKind.Local).AddTicks(1718),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7599)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Fantastik",
                            CreatedDate = new DateTime(2024, 6, 7, 12, 32, 56, 875, DateTimeKind.Local).AddTicks(1494),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7601)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Belgesel",
                            CreatedDate = new DateTime(2025, 5, 21, 9, 59, 19, 993, DateTimeKind.Local).AddTicks(8165),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7603)
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Animasyon",
                            CreatedDate = new DateTime(2024, 11, 22, 17, 52, 32, 459, DateTimeKind.Local).AddTicks(2202),
                            ModifiedDate = new DateTime(2025, 11, 27, 15, 13, 29, 245, DateTimeKind.Local).AddTicks(7605)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MembershipPlanId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Domain.Entities.MemberMovieList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberMovieLists");
                });

            modelBuilder.Entity("Domain.Entities.MemberMovieListItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberMovieListId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MemberMovieListId");

                    b.HasIndex("MovieId");

                    b.ToTable("MemberMovieListItems");
                });

            modelBuilder.Entity("Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxChangePerMonth")
                        .HasColumnType("int");

                    b.Property<int>("MaxMoviesPerMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.HasOne("Domain.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("Domain.Entities.MemberMovieList", b =>
                {
                    b.HasOne("Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Domain.Entities.MemberMovieListItem", b =>
                {
                    b.HasOne("Domain.Entities.MemberMovieList", "MemberMovieList")
                        .WithMany("Items")
                        .HasForeignKey("MemberMovieListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberMovieList");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Domain.Entities.MemberMovieList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
