// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilmDukkaniDbContext))]
    [Migration("20251127105227_AddMembershipPlanEntity")]
    partial class AddMembershipPlanEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Aksiyon",
                            CreatedDate = new DateTime(2025, 10, 9, 18, 51, 57, 69, DateTimeKind.Local).AddTicks(4190),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1650)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Macera",
                            CreatedDate = new DateTime(2025, 10, 7, 6, 59, 44, 351, DateTimeKind.Local).AddTicks(5585),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1654)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Dram",
                            CreatedDate = new DateTime(2024, 5, 10, 5, 23, 40, 365, DateTimeKind.Local).AddTicks(3186),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1656)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Korku",
                            CreatedDate = new DateTime(2024, 11, 18, 22, 26, 48, 285, DateTimeKind.Local).AddTicks(1623),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1658)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Bilim Kurgu",
                            CreatedDate = new DateTime(2024, 4, 23, 14, 41, 58, 987, DateTimeKind.Local).AddTicks(6597),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1659)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Komedi",
                            CreatedDate = new DateTime(2024, 4, 1, 19, 34, 38, 709, DateTimeKind.Local).AddTicks(4017),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1662)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Gerilim",
                            CreatedDate = new DateTime(2025, 7, 29, 6, 17, 34, 699, DateTimeKind.Local).AddTicks(5782),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1663)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Fantastik",
                            CreatedDate = new DateTime(2024, 6, 7, 11, 11, 54, 306, DateTimeKind.Local).AddTicks(5558),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1665)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Belgesel",
                            CreatedDate = new DateTime(2025, 5, 21, 8, 38, 17, 425, DateTimeKind.Local).AddTicks(2229),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1666)
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Animasyon",
                            CreatedDate = new DateTime(2024, 11, 22, 16, 31, 29, 890, DateTimeKind.Local).AddTicks(6266),
                            ModifiedDate = new DateTime(2025, 11, 27, 13, 52, 26, 677, DateTimeKind.Local).AddTicks(1669)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxChangePerMonth")
                        .HasColumnType("int");

                    b.Property<int>("MaxMoviesPerMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
