// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilmDukkaniDbContext))]
    [Migration("20251127114343_MakeMembershipPlanRequiredForMember")]
    partial class MakeMembershipPlanRequiredForMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Aksiyon",
                            CreatedDate = new DateTime(2025, 10, 9, 19, 43, 13, 684, DateTimeKind.Local).AddTicks(1929),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9388)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Macera",
                            CreatedDate = new DateTime(2025, 10, 7, 7, 51, 0, 966, DateTimeKind.Local).AddTicks(3323),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9392)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Dram",
                            CreatedDate = new DateTime(2024, 5, 10, 6, 14, 56, 980, DateTimeKind.Local).AddTicks(925),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9395)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Korku",
                            CreatedDate = new DateTime(2024, 11, 18, 23, 18, 4, 899, DateTimeKind.Local).AddTicks(9362),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9396)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Bilim Kurgu",
                            CreatedDate = new DateTime(2024, 4, 23, 15, 33, 15, 602, DateTimeKind.Local).AddTicks(4335),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9398)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Komedi",
                            CreatedDate = new DateTime(2024, 4, 1, 20, 25, 55, 324, DateTimeKind.Local).AddTicks(1756),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9401)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Gerilim",
                            CreatedDate = new DateTime(2025, 7, 29, 7, 8, 51, 314, DateTimeKind.Local).AddTicks(3520),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9402)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Fantastik",
                            CreatedDate = new DateTime(2024, 6, 7, 12, 3, 10, 921, DateTimeKind.Local).AddTicks(3297),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9404)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Belgesel",
                            CreatedDate = new DateTime(2025, 5, 21, 9, 29, 34, 39, DateTimeKind.Local).AddTicks(9968),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9406)
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Animasyon",
                            CreatedDate = new DateTime(2024, 11, 22, 17, 22, 46, 505, DateTimeKind.Local).AddTicks(4005),
                            ModifiedDate = new DateTime(2025, 11, 27, 14, 43, 43, 291, DateTimeKind.Local).AddTicks(9408)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MembershipPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MembershipPlanId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxChangePerMonth")
                        .HasColumnType("int");

                    b.Property<int>("MaxMoviesPerMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.HasOne("Domain.Entities.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
