// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilmDukkaniDbContext))]
    [Migration("20251126083914_AddMemberEntity")]
    partial class AddMemberEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Aksiyon",
                            CreatedDate = new DateTime(2025, 10, 8, 16, 38, 44, 329, DateTimeKind.Local).AddTicks(4029),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1492)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Macera",
                            CreatedDate = new DateTime(2025, 10, 6, 4, 46, 31, 611, DateTimeKind.Local).AddTicks(5428),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1497)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Dram",
                            CreatedDate = new DateTime(2024, 5, 9, 3, 10, 27, 625, DateTimeKind.Local).AddTicks(3029),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1499)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Korku",
                            CreatedDate = new DateTime(2024, 11, 17, 20, 13, 35, 545, DateTimeKind.Local).AddTicks(1466),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1501)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Bilim Kurgu",
                            CreatedDate = new DateTime(2024, 4, 22, 12, 28, 46, 247, DateTimeKind.Local).AddTicks(6440),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1503)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Komedi",
                            CreatedDate = new DateTime(2024, 3, 31, 17, 21, 25, 969, DateTimeKind.Local).AddTicks(3861),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1505)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Gerilim",
                            CreatedDate = new DateTime(2025, 7, 28, 4, 4, 21, 959, DateTimeKind.Local).AddTicks(5625),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1507)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Fantastik",
                            CreatedDate = new DateTime(2024, 6, 6, 8, 58, 41, 566, DateTimeKind.Local).AddTicks(5402),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1509)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Belgesel",
                            CreatedDate = new DateTime(2025, 5, 20, 6, 25, 4, 685, DateTimeKind.Local).AddTicks(2073),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1510)
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Animasyon",
                            CreatedDate = new DateTime(2024, 11, 21, 14, 18, 17, 150, DateTimeKind.Local).AddTicks(6110),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 39, 13, 937, DateTimeKind.Local).AddTicks(1513)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
