// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FilmDukkaniDbContext))]
    [Migration("20251126082853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Aksiyon",
                            CreatedDate = new DateTime(2025, 10, 8, 16, 28, 23, 525, DateTimeKind.Local).AddTicks(6605),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4064)
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Macera",
                            CreatedDate = new DateTime(2025, 10, 6, 4, 36, 10, 807, DateTimeKind.Local).AddTicks(8000),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4069)
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Dram",
                            CreatedDate = new DateTime(2024, 5, 9, 3, 0, 6, 821, DateTimeKind.Local).AddTicks(5601),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4071)
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Korku",
                            CreatedDate = new DateTime(2024, 11, 17, 20, 3, 14, 741, DateTimeKind.Local).AddTicks(4038),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4073)
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Bilim Kurgu",
                            CreatedDate = new DateTime(2024, 4, 22, 12, 18, 25, 443, DateTimeKind.Local).AddTicks(9012),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4075)
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Komedi",
                            CreatedDate = new DateTime(2024, 3, 31, 17, 11, 5, 165, DateTimeKind.Local).AddTicks(6432),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4077)
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Gerilim",
                            CreatedDate = new DateTime(2025, 7, 28, 3, 54, 1, 155, DateTimeKind.Local).AddTicks(8197),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4079)
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Fantastik",
                            CreatedDate = new DateTime(2024, 6, 6, 8, 48, 20, 762, DateTimeKind.Local).AddTicks(7973),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4080)
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Belgesel",
                            CreatedDate = new DateTime(2025, 5, 20, 6, 14, 43, 881, DateTimeKind.Local).AddTicks(4644),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4082)
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Animasyon",
                            CreatedDate = new DateTime(2024, 11, 21, 14, 7, 56, 346, DateTimeKind.Local).AddTicks(8681),
                            ModifiedDate = new DateTime(2025, 11, 26, 11, 28, 53, 133, DateTimeKind.Local).AddTicks(4084)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
